apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  namespace: kul
  labels:
    app: tomcat
    version: "10.0.8"
spec:
  containers:
    - name: tomcat
      image: kulbhushanmayer/tomcat:10.0.8
      ### To download or not to download the image before container creation
      imagePullPolicy: Always # else IfNotPresent # or Never
      resources:
        requests:
          cpu: "125m"
          memory: "125Mi"
        limits:
          cpu: "250m"
          memory: "250Mi"
      env:
        - name: DB_PORT
          value: 3306
        - name: QUEUE_MANAGER_URL
          value: https://queuemanager:23012
