apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  namespace: kul
  labels:
    app: tomcat
    version: "10.0.8"
spec:
  containers:
    - name: tomcat
      image: kulbhushanmayer/tomcat:10.0.8
      resources:
        requests:
          cpu: "125m"
          memory: "125Mi"
        limits:
          cpu: "250m"
          memory: "250Mi"
