### Namespace
apiVersion: v1
kind: Namespace
metadata:     
  name: postgres
--- 
### Secret
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: postgres
type: Opeque
data: 
  DB_PWD: aW5kaWExMjM=
---
### ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  namespace: postgres
  labels:
    app: postgres
data:
  DB_USER: postgres
---
### POD
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: postgres
  labels:
    app: postgres
    version: "13"
spec:
  containers:
    - name: postgres
      image: postgres:13.4
      resources:
        requests:
          memory: "64Mi"
          cpu: "125m"
        limits:
          memory: "128Mi"
          cpu: "250m"
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: DB_PWD
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres
              key: DB_USER
      volumeMounts:
        - name: postgres
          mountPath: "/var/lib/postgresql/data"
      ports:
        - containerPort: 5432
          name: postgres
  volumes:
    - name: postgres
      hostPath:
        path: /postgres
        type: "DirectoryOrCreate"
