apiVersion: v1
kind: Service ## This is internal loadbalancer
metadata:
  name: postgres
  namespace: postgres
  labels:
    app: postgres
spec:
  selector: # to identify the pod to divert the traffic, using the label applied on the pod mentioned inside the pod-template definition
    app: postgres
  type: ClusterIP 
  # ClusterIP for traffic within the k8s cluster,
  # NodePort for Traffic coming from outside the cluster
  # LoadBalancer used with Kubernetes as a Service with external LoadBalancer configured automatically
  ports: ## POrts on which Service will listen
    - port: 80 # Service port
      protocol: TCP
      targetPort: postgres # POD port on which finally traffic is diverted
  clusterIP: 10.109.232.78
