apiVersion: apps/v1
kind: Deployment
metadata:
  name: thinknyx
  namespace: thinknyx
spec:
  selector:
    matchLabels:
      app: thinknyx
  template:
    metadata:
      labels:
        app: thinknyx
    spec:
      containers:
      - name: thinknyx
        image: kulbhushanmayer/nodejs-app:v1
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 4000
          name: thinknyx
        envFrom:
          - configMapRef:
              name: thinknyx
          - secretRef:
              name: thinknyx
