apiVersion: apps/v1
kind: Deployment
metadata:
  name: thinknyx
  namespace: thinknyx
spec:
  selector:
    matchLabels:
      app: thinknyx
  template:
    metadata:
      labels:
        app: thinknyx
    spec:
      containers:
      - name: thinknyx
        image: kulbhushanmayer/nodejs-app:v1
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 4000
          name: thinknyx
        envFrom:
          - configMapRef:
              name: thinknyx
          - secretRef:
              name: thinknyx
      initContainers: ## These containers will start before actual application, are used for environment setup, or enviroment checks
      - name: database-setup
        image: kulbhushanmayer/nodejs-app:database-setup
        command:
        - "sh"
        - "-c"
        - "sh database_setup.sh && sleep 30"
        envFrom:
        - configMapRef:
            name: thinknyx
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: thinknyx
              key: DB_PWD
