apiVersion: apps/v1
kind: Deployment
metadata:
  name: thinknyx
  namespace: thinknyx
spec:
  selector:
    matchLabels:
      app: thinknyx
  template:
    metadata:
      labels:
        app: thinknyx
    spec:
      containers:
      - name: thinknyx
        image: kulbhushanmayer/nodejs-app:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
